// This is the configuration file. Ideally, any configuration and calibration
// of the device should be done by changing this file only.

// Needed by util/delay.h
#define F_CPU 16000000UL

// Delay between two executions of main loop, given in millisecond.
#define LOOP_DELAY 20

// One secind, given in units of LOOP_DELAY
#define SECOND  50
// One secind, given in units of LOOP_DELAY
#define DECI_SECOND  5

// Definition of indicator pin.
#define INDICATOR_DATA_DIR DDRE
#define INDICATOR_DATA_DIR_PIN DDE1
#define INDICATOR_DATA PORTE
#define INDICATOR_DATA_PIN PORTE1

// Half length of one complete indicator period. In other words, the time the
// indicator spends on and off. Given in units of LOOP_DELAY.
#define INDICATOR_HALF_PERIOD 25

// Definition of flush button pin.
#define FLUSH_BUTTON_DATA_DIR DDRE
#define FLUSH_BUTTON_DATA_DIR_PIN DDE2
#define FLUSH_BUTTON_DATA PORTE
#define FLUSH_BUTTON_DATA_PIN PORTE2
#define FLUSH_BUTTON_INPUT PINE
#define FLUSH_BUTTON_INPUT_PIN PINE2


// Definition of valve control pins
#define VALVE_MIDDLE_DATA_DIR DDRB
#define VALVE_MIDDLE_DATA_DIR_PIN DDB1
#define VALVE_MIDDLE_DATA PORTB
#define VALVE_MIDDLE_DATA_PIN PORTB1
#define VALVE_MIDDLE_DATA_REF B

#define VALVE_INNER_0_DATA_DIR DDRD
#define VALVE_INNER_0_DATA_DIR_PIN DDD0
#define VALVE_INNER_0_DATA PORTD
#define VALVE_INNER_0_DATA_PIN PORTD0
#define VALVE_INNER_0_DATA_REF D

#define VALVE_INNER_1_DATA_DIR DDRB
#define VALVE_INNER_1_DATA_DIR_PIN DDB2
#define VALVE_INNER_1_DATA PORTB
#define VALVE_INNER_1_DATA_PIN PORTB2
#define VALVE_INNER_1_DATA_REF B

#define VALVE_INNER_2_DATA_DIR DDRB
#define VALVE_INNER_2_DATA_DIR_PIN DDB3
#define VALVE_INNER_2_DATA PORTB
#define VALVE_INNER_2_DATA_PIN PORTB3
#define VALVE_INNER_2_DATA_REF B

#define VALVE_INNER_3_DATA_DIR DDRD
#define VALVE_INNER_3_DATA_DIR_PIN DDD1
#define VALVE_INNER_3_DATA PORTD
#define VALVE_INNER_3_DATA_PIN PORTD1
#define VALVE_INNER_3_DATA_REF D

#define VALVE_INNER_4_DATA_DIR DDRC
#define VALVE_INNER_4_DATA_DIR_PIN DDC7
#define VALVE_INNER_4_DATA PORTC
#define VALVE_INNER_4_DATA_PIN PORTC7
#define VALVE_INNER_4_DATA_REF C

#define VALVE_INNER_5_DATA_DIR DDRC
#define VALVE_INNER_5_DATA_DIR_PIN DDC6
#define VALVE_INNER_5_DATA PORTC
#define VALVE_INNER_5_DATA_PIN PORTC6
#define VALVE_INNER_5_DATA_REF C

#define VALVE_OUTER_0_DATA_DIR DDRD
#define VALVE_OUTER_0_DATA_DIR_PIN DDD2
#define VALVE_OUTER_0_DATA PORTC
#define VALVE_OUTER_0_DATA_PIN PORTD2
#define VALVE_OUTER_0_DATA_REF D

// Note: OUTER_1 and OUTER_2 inverted due to error in tube placement
#define VALVE_OUTER_2_DATA_DIR DDRC
#define VALVE_OUTER_2_DATA_DIR_PIN DDC5
#define VALVE_OUTER_2_DATA PORTC
#define VALVE_OUTER_2_DATA_PIN PORTC5
#define VALVE_OUTER_2_DATA_REF C

#define VALVE_OUTER_1_DATA_DIR DDRC
#define VALVE_OUTER_1_DATA_DIR_PIN DDC4
#define VALVE_OUTER_1_DATA PORTC
#define VALVE_OUTER_1_DATA_PIN PORTC4
#define VALVE_OUTER_1_DATA_REF C

#define VALVE_OUTER_3_DATA_DIR DDRD
#define VALVE_OUTER_3_DATA_DIR_PIN DDD3
#define VALVE_OUTER_3_DATA PORTD
#define VALVE_OUTER_3_DATA_PIN PORTD3
#define VALVE_OUTER_3_DATA_REF D

#define VALVE_OUTER_4_DATA_DIR DDRC
#define VALVE_OUTER_4_DATA_DIR_PIN DDC3
#define VALVE_OUTER_4_DATA PORTC
#define VALVE_OUTER_4_DATA_PIN PORTC3
#define VALVE_OUTER_4_DATA_REF C

// Note: OUTER_6 and OUTER_5 inverted due to error in tube placement
#define VALVE_OUTER_6_DATA_DIR DDRC
#define VALVE_OUTER_6_DATA_DIR_PIN DDC2
#define VALVE_OUTER_6_DATA PORTC
#define VALVE_OUTER_6_DATA_PIN PORTC2
#define VALVE_OUTER_6_DATA_REF C

#define VALVE_OUTER_5_DATA_DIR DDRD
#define VALVE_OUTER_5_DATA_DIR_PIN DDD4
#define VALVE_OUTER_5_DATA PORTD
#define VALVE_OUTER_5_DATA_PIN PORTD4
#define VALVE_OUTER_5_DATA_REF D

#define VALVE_OUTER_7_DATA_DIR DDRC
#define VALVE_OUTER_7_DATA_DIR_PIN DDC1
#define VALVE_OUTER_7_DATA PORTC
#define VALVE_OUTER_7_DATA_PIN PORTC1
#define VALVE_OUTER_7_DATA_REF C

#define VALVE_OUTER_8_DATA_DIR DDRC
#define VALVE_OUTER_8_DATA_DIR_PIN DDC0
#define VALVE_OUTER_8_DATA PORTC
#define VALVE_OUTER_8_DATA_PIN PORTC0
#define VALVE_OUTER_8_DATA_REF C

#define VALVE_OUTER_9_DATA_DIR DDRD
#define VALVE_OUTER_9_DATA_DIR_PIN DDD5
#define VALVE_OUTER_9_DATA PORTD
#define VALVE_OUTER_9_DATA_PIN PORTD5
#define VALVE_OUTER_9_DATA_REF D

#define VALVE_OUTER_10_DATA_DIR DDRD
#define VALVE_OUTER_10_DATA_DIR_PIN DDD7
#define VALVE_OUTER_10_DATA PORTD
#define VALVE_OUTER_10_DATA_PIN PORTD7
#define VALVE_OUTER_10_DATA_REF D

#define VALVE_OUTER_11_DATA_DIR DDRD
#define VALVE_OUTER_11_DATA_DIR_PIN DDD6
#define VALVE_OUTER_11_DATA PORTD
#define VALVE_OUTER_11_DATA_PIN PORTD6
#define VALVE_OUTER_11_DATA_REF D

// Length of valve opening during a drop, given in units of LOOP_DELAY
#define DROP_SIZE 4
// Time between two different shapes, given in units of LOOP_DELAY
#define PATTERN_INTERVAL (10*SECOND)

// Length of initialization time when all valves are open, given in units of
// LOOP_DELAY
#define INITIALIZATION_DURATION (90*SECOND)
// Length of time after initialization before sequence start, given in units of
// LOOP_DELAY
#define INITIALIZATION_COOLDOWN (5*SECOND)
